### ISSUE TITLE
Assignment range issue

### ISSUE THREAD

**Issue by guillaumejacquart** [flagship-io/flagship-android#1]
Hash comparison with variation cumulative allocation traffic should be '<' instead of '<='.
Example: 
v1 : 50%
v2 : 50%

if hash % 100 == 50, it should be assigned to v2 (instead of v1 actually). [0;49[ contains actually 50 digits, the same as [50;100[

https://github.com/abtasty/flagship-android/blob/5f8454afee0f12519162069be279ea390ad8828a/src/main/java/com/abtasty/flagship/model/Campaign.kt#L145

**Comment by raf-abtasty** [comment]
It has been fixed in the v3.0.0. Thx
