### ISSUE TITLE
Default value is picked for modifications

### ISSUE THREAD

**Issue by damiafuentes** [flagship-io/flagship-android#4]
Default value is picked for all modifications starting on November 10th. Before that date everything was working correctly. I am not sure how to debug the library to be able to provide more information. However, that is happening to all of our users where before it wasn't happening.

**Comment by guillaumejacquart** [comment]
Hey @damiafuentes thanks for bringing that issue to us.
Could you tell us for which account you encountered this issue (or environment ID) ? 
We need that information to check the use cases setup in the platform.

**Comment by damiafuentes** [comment]
I've added logs and found this error:

```
Flagship.getModification("is_social_logins_enabled", false)
```
```
Flagship.getValue "is_social_logins_enabled"  types are different. Default value is returned.
```

When Flagship is retrieving the modifications the data is downloaded correctly. For that specific key the logs print:

```
is_social_logins_enabled=Modification(key=is_social_logins_enabled,
campaignId=c5gbbb67b6e2l79md7b0,
variationGroupId=c66l1k4h8hb02dnrm25g,
variationId=c66l1k4h8hb02dnrm260,
variationReference=false,
value={
  "type": "boolean",
  "value": true
})
```

**Comment by damiafuentes** [comment]
Looks like the API response has changed from returning a `boolean` to return a `JSONObject`.
